FROM golang:1.24

# Установка зависимостей
#RUN go install github.com/swaggo/swag/cmd/swag@latest

WORKDIR /app

# Установка goose
RUN go install github.com/pressly/goose/v3/cmd/goose@latest

# Добавляем goose в PATH
ENV PATH="/go/bin:${PATH}"

CMD ["goose", "--help"]