FROM golang:1.24

# Установка зависимостей
#RUN apk add --no-cache git

WORKDIR /app

# Установка goose
RUN go install github.com/pressly/goose/v3/cmd/goose@latest

# Добавляем goose в PATH
ENV PATH="/go/bin:${PATH}"

# Миграции будут монтироваться через volume из хоста
# COPY migrations /app/migrations  # ← не нужно, volume заменит

CMD ["goose", "--help"]